### ISSUE TITLE
Error comando !invite cuando el usuario objetivo no está registrado

### ISSUE THREAD

**Issue by latra** [LleidaHack/hackeps-2020-discordbot#21]
Cuando se realiza el comando
`eps!invite <Usuario>`
, si el usuario objetivo no está registrado en la base de datos, se genera la siguiente excepción:

```
DEBUG:discord.client:Dispatching event command_error
Ignoring exception in command invite:
Traceback (most recent call last):
  File "C:\Users\Propietario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Lleidahack\hackeps-2020-discordbot\hackeps-2020-discordbot\src\modules\discord_bot.py", line 53, in invite
    await self.invite_command(ctx)
  File "D:\Lleidahack\hackeps-2020-discordbot\hackeps-2020-discordbot\src\modules\discord_bot.py", line 181, in invite_command
    logging.info(f"Gente encontrada: {[p.username for p in people]}")
  File "D:\Lleidahack\hackeps-2020-discordbot\hackeps-2020-discordbot\src\modules\discord_bot.py", line 181, in <listcomp>
    logging.info(f"Gente encontrada: {[p.username for p in people]}")
AttributeError: 'NoneType' object has no attribute 'username'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\Propietario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Propietario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Propietario\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'username'
```

![image](https://user-images.githubusercontent.com/17687435/99739818-ed21a700-2acd-11eb-95ca-174b8545ea9c.png)
La ejecución del programa debería devolver true en el condicional de la línea 177 de discord_bot.py.

**Comment by latra** [comment]
solucionado
